# aura-glass design tokens — the single source of truth for every value that
# is written down in more than one place.
#
# This file is sourced, not templated. GTK4's var() fails at computed-value
# time rather than parse time (see the header of css/gtk4-transparency.css for
# the surface-blanking bug that caused), St has no custom properties at all,
# and GTK3's CSS engine predates them — so there is no cross-toolkit way to
# express a shared number as a variable. Generating the CSS from templates was
# the other option and was rejected: every non-obvious number in css/ carries a
# comment explaining why it is that number, and those comments are the most
# valuable thing in this repository.
#
# So the values still live literally in the files that use them, and this file
# plus tools/check-tokens.sh make the duplication *checked* instead of trusted.
# Change a value here, run tools/check-tokens.sh, and it names every file still
# disagreeing. That is the whole mechanism.
#
# Each token's comment lists every consumer. Keep those lists accurate — the
# checker's manifest is derived from the same pairings, and a token whose
# consumers are undocumented is a token that will drift again.

# ---------- Radii ----------
#
# The project rule, repeated in css/gtk3-tweaks.css and css/shell-tweaks.css:
# a painted radius must always equal the blur radius behind it. Blur My Shell
# rounds the blur actor; the CSS rounds the surface drawn on top of it. When
# they disagree the smaller shape leaves a sliver of the larger one showing,
# which reads as a rendering fault rather than as a wrong number.

# Window corners. The theme's libadwaita override already paints
# `window { border-radius: 30px }`; GTK3 windows and the blur behind every
# window have to agree with it.
#
# css/gtk4-70-surfaces.css restates it at the same value, which is a duplicate
# of the theme's rule while the preset is `default` and the whole point of the
# entry the moment it is not: the theme's copy is regenerated by the theme's own
# installer and is not ours to rewrite, so a preset has to out-rank it instead.
# Our block is appended after the theme's, so equal specificity is enough.
#   css/gtk3-tweaks.css       decoration, .titlebar/.titlebar.background
#   css/gtk4-70-surfaces.css  window, window.background, window.csd
#   dconf/core.ini            [blur-my-shell/applications] corner-radius
TOKEN_RADIUS_WINDOW=30

# Ordinary popup menus.
#   css/shell-20-popup-menus.css  .popup-menu-content
#   css/shell-popup-blur.css      .popup-menu-content, at !important
#   dconf/core.ini                [blur-my-shell/popup] menu-corner-radius
TOKEN_RADIUS_MENU=26

# Quick Settings, the date menu and the quick-toggle menu (the Wi-Fi/Bluetooth
# device list under a toggle's arrow). Blur My Shell groups these three with
# each other rather than with .popup-menu-content — its popup component
# matches on style class, and 'quick-settings', 'quick-toggle-menu' and
# 'datemenu-popover' share one key. That is why the date menu and quick-toggle
# menu are not on TOKEN_RADIUS_MENU despite also being .popup-menu-content, and
# it is not guessable from the selector.
#   css/shell-20-popup-menus.css  .datemenu-popover, .quick-toggle-menu,
#                                 .popup-menu-content.quick-settings
#   css/shell-popup-blur.css      .datemenu-popover and .quick-toggle-menu
#                                 again, at !important — that sheet is spliced
#                                 last and its .popup-menu-content rule would
#                                 otherwise repaint both at TOKEN_RADIUS_MENU
#   dconf/core.ini                [blur-my-shell/popup] quick-settings-corner-radius
TOKEN_RADIUS_QUICK_SETTINGS=33

# Notifications, both in the calendar popup and as arriving banners.
#
# The two stacked states are on this token as well. They have no blur behind
# them to disagree with — nothing rounds them — but they are the same card
# peeking out from behind the top one, so what they can disagree with is
# .message itself, and a stack showing a rounder corner than the card in front
# of it reads as a rendering fault in exactly the way the project rule above
# describes.
#   css/shell-30-notifications.css  .message, .notification-banner,
#                                   .message:second-in-stack,
#                                   .message:lower-in-stack
#   css/shell-80-solid.css          both stacked states again, repainted opaque
#   dconf/core.ini        [blur-my-shell/popup] notification-corner-radius
TOKEN_RADIUS_NOTIFICATION=20

# Modal dialogs (log out, restart, power off).
#   css/shell-tweaks.css  .modal-dialog, .end-session-dialog
#   dconf/core.ini        [blur-my-shell/popup] dialog-corner-radius
TOKEN_RADIUS_DIALOG=20

# The generic popup fallback, for surfaces the more specific keys above do not
# claim. dconf only — nothing in css/ paints against it.
#   dconf/core.ini        [blur-my-shell/popup] corner-radius
TOKEN_RADIUS_POPUP=20

# The volume/brightness OSD. dconf only: Custom OSD draws the pill and Blur My
# Shell rounds the blur, so there is no CSS counterpart to keep in step.
#
# This key does NOT clamp, whatever the old comment in dconf/core.ini claimed.
# Past half the blurred box's height the four corner arcs overlap and the OSD
# turns into a soft ellipse — which is what 100 produced. The box being blurred
# is the stock .osd-window, far shorter than the pill Custom OSD draws inside
# it, so any value estimated from the *pill* comes out far too large. 12 was
# found by bisecting 0 (hard rectangle) against 25 (bulging). Raise it only
# against a screenshot.
#   dconf/core.ini        [blur-my-shell/popup] osd-corner-radius
TOKEN_RADIUS_OSD=12

# Buttons carrying a label — Apply, Save, and the rest of gtk4-20-buttons.css's
# own button.text-button block. Shipped as a pill (9999) rather than a curated
# pixel figure: 9999 is a sentinel a border-radius this side of a button's own
# height always clips to a full capsule, so `pill` and `default` both read as
# 9999 and stay a capsule at any button height, the same way the theme's own
# blanket `button { border-radius: 9999px }` already did before this block
# existed. Bounded by radius_bounds() up to 9999, not by the flat/rounded
# ladder the other six columns share: it is not part of the picture those six
# were bisected against, and RADIUS_MAX_BUTTON exists to let it move
# independently of them.
#   css/gtk4-20-buttons.css  button.text-button, button.flat.text-button,
#                            button.pill
TOKEN_RADIUS_BUTTON=9999

# ---------- Radius presets ----------
#
# The eight values above are the `default` row of the table below, and the only
# row the shipped files are written at. --radius-preset picks a different row,
# and lib/steps-css.sh + lib/steps-dconf.sh apply it to the *installed* copies
# — never to css/ or dconf/core.ini, which stay at `default` so that
# tools/check-tokens.sh keeps checking one known state.
#
# Curated rows rather than a slider or a multiplier, because these numbers are
# not proportional to each other and scaling them by a common factor produces
# combinations nobody looked at. Quick Settings is *larger* than a menu (Blur My
# Shell groups the date menu with it, see TOKEN_RADIUS_QUICK_SETTINGS above),
# and the OSD's ceiling has nothing to do with the others at all — it is set by
# the height of the box being blurred, not by the shape drawn inside it.
#
# The OSD column is the one to be careful with. TOKEN_RADIUS_OSD's comment
# records why: past half the blurred box's height the four corner arcs overlap
# and the pill turns into a soft ellipse, which is what 25 produced. Every row
# here stays well under that.
#
# The `default` row is the one that has been through the screenshot loop that
# tokens.sh describes. The others are coherent by construction — they keep the
# ladder between surfaces the default row establishes — but each is worth a
# pass of `tools/preview.sh` before being called finished, per the project rule
# that a radius is raised against a screenshot rather than against an estimate.
#
# Six rows rather than the four this shipped with, and `rounded` is now the
# ceiling. The old table put `default` in the middle of it and reached 46px at
# `pill`, which nobody wanted: past the shipped 30px a window corner starts
# eating its own content, and the two rows above default were there because the
# table looked lopsided without them rather than because anyone asked for a
# rounder window. So the range now runs *down* from default — flat, sharp, soft
# and medium below it, rounded as the single step above — which is the
# direction people actually move this.
#
# `pill` is gone. install.sh still accepts the name and resolves it to
# `rounded`, because it was a --radius-preset anyone could have run and the
# memo it wrote is still sitting in $CONF_DIR on those machines.
#
# `adwaita` is the one row not bisected against this project's own screenshots
# — it is pinned to libadwaita's own shipped corners instead, for a desktop
# that wants this theme's windows to match an unthemed GTK4 app's. It sits
# between `sharp` and `soft` because 12px does. Button stays at the sentinel
# 9999 here (a capsule, same as `default`) rather than dropping to a pixel
# figure — libadwaita's own flat buttons are not the pill this project's are,
# so there is no libadwaita number to pin the button column to.
RADIUS_PRESETS="flat sharp adwaita soft medium default rounded"

# Set the eight TOKEN_RADIUS_* values for a preset. Fails on an unknown name
# rather than falling back to default: a typo in --radius-preset that silently
# installed the shipped look would be indistinguishable from the flag working.
radius_preset_values() {
    case "${1:-}" in
        flat)
            TOKEN_RADIUS_WINDOW=6
            TOKEN_RADIUS_MENU=5
            TOKEN_RADIUS_QUICK_SETTINGS=6
            TOKEN_RADIUS_NOTIFICATION=4
            TOKEN_RADIUS_DIALOG=4
            TOKEN_RADIUS_POPUP=4
            TOKEN_RADIUS_OSD=2
            TOKEN_RADIUS_BUTTON=4
            ;;
        sharp)
            TOKEN_RADIUS_WINDOW=10
            TOKEN_RADIUS_MENU=8
            TOKEN_RADIUS_QUICK_SETTINGS=10
            TOKEN_RADIUS_NOTIFICATION=6
            TOKEN_RADIUS_DIALOG=6
            TOKEN_RADIUS_POPUP=6
            TOKEN_RADIUS_OSD=4
            TOKEN_RADIUS_BUTTON=6
            ;;
        # Pinned to libadwaita's own shipped corners rather than bisected —
        # see the RADIUS_PRESETS comment above. Quick Settings is not
        # libadwaita's to have an opinion on (it is a shell surface, not a
        # GTK4 one), so it keeps this row's place in the flat/sharp/soft
        # ladder instead: between sharp's 10 and soft's 17.
        adwaita)
            TOKEN_RADIUS_WINDOW=12
            TOKEN_RADIUS_MENU=12
            TOKEN_RADIUS_QUICK_SETTINGS=18
            TOKEN_RADIUS_NOTIFICATION=12
            TOKEN_RADIUS_DIALOG=12
            TOKEN_RADIUS_POPUP=12
            TOKEN_RADIUS_OSD=12
            TOKEN_RADIUS_BUTTON=6
            ;;
        soft)
            TOKEN_RADIUS_WINDOW=16
            TOKEN_RADIUS_MENU=14
            TOKEN_RADIUS_QUICK_SETTINGS=17
            TOKEN_RADIUS_NOTIFICATION=10
            TOKEN_RADIUS_DIALOG=10
            TOKEN_RADIUS_POPUP=10
            TOKEN_RADIUS_OSD=6
            TOKEN_RADIUS_BUTTON=8
            ;;
        medium)
            TOKEN_RADIUS_WINDOW=22
            TOKEN_RADIUS_MENU=19
            TOKEN_RADIUS_QUICK_SETTINGS=24
            TOKEN_RADIUS_NOTIFICATION=15
            TOKEN_RADIUS_DIALOG=15
            TOKEN_RADIUS_POPUP=15
            TOKEN_RADIUS_OSD=9
            TOKEN_RADIUS_BUTTON=10
            ;;
        default)
            TOKEN_RADIUS_WINDOW=30
            TOKEN_RADIUS_MENU=26
            TOKEN_RADIUS_QUICK_SETTINGS=33
            TOKEN_RADIUS_NOTIFICATION=20
            TOKEN_RADIUS_DIALOG=20
            TOKEN_RADIUS_POPUP=20
            TOKEN_RADIUS_OSD=12
            TOKEN_RADIUS_BUTTON=9999
            ;;
        rounded)
            TOKEN_RADIUS_WINDOW=38
            TOKEN_RADIUS_MENU=32
            TOKEN_RADIUS_QUICK_SETTINGS=40
            TOKEN_RADIUS_NOTIFICATION=26
            TOKEN_RADIUS_DIALOG=26
            TOKEN_RADIUS_POPUP=26
            TOKEN_RADIUS_OSD=16
            TOKEN_RADIUS_BUTTON=9999
            ;;
        # Retired, and still answered. It was a --radius-preset people ran, and
        # the memo it wrote in $CONF_DIR is read back by every later flagless
        # install — so removing the name outright would fail those runs at
        # `unknown --radius-preset` rather than quietly doing the old thing.
        # Which row it resolves to is radius_preset_canonical's answer, not a
        # second copy of it.
        pill)
            radius_preset_values "$(radius_preset_canonical pill)"
            ;;
        *)  return 1 ;;
    esac
}

# What a preset name resolves to — itself for every current row, and the row
# that replaced it for a retired one.
#
# One place names the mapping, because two would eventually disagree: this is
# what radius_preset_values() reads to answer `pill`, and what apply_radius_css
# writes the memo at. A memo used to be written at whatever name was typed, so a
# machine that installed `pill` kept saying `pill` for good and every later
# reader had to know a name that no longer names a row. It now records the row.
# RADIUS_PRESET_ALIASES in gui/aura_glass_settings.py is this same map for the
# settings window, which reads that memo directly.
#
# `custom` and anything unknown come back unchanged: this resolves names, it
# does not validate them — radius_preset_values() is what rejects a typo.
radius_preset_canonical() {
    case "${1:-}" in
        pill) printf 'rounded\n' ;;
        *)    printf '%s\n' "${1:-}" ;;
    esac
}

# The range each radius may be set to by hand.
#
# The six rows above are curated because these numbers are not proportional to
# each other, and that is still true — but "pick one of six" and "type any
# number" are not the only two options. The window offers a control per surface
# bounded by what the curated rows already establish as sane: the `flat` row to
# the `rounded` row, which is the range someone looked at.
#
# The ceiling came down with the table. It used to be `pill`'s 46px window and
# 52px Quick Settings; `rounded` is now the top row, so it is now the top of
# the range a spin row can reach.
radius_bounds() {
    RADIUS_MIN_WINDOW=6;           RADIUS_MAX_WINDOW=38
    RADIUS_MIN_MENU=5;             RADIUS_MAX_MENU=32
    RADIUS_MIN_QUICK_SETTINGS=6;   RADIUS_MAX_QUICK_SETTINGS=40
    RADIUS_MIN_NOTIFICATION=4;     RADIUS_MAX_NOTIFICATION=26
    RADIUS_MIN_DIALOG=4;           RADIUS_MAX_DIALOG=26
    RADIUS_MIN_POPUP=4;            RADIUS_MAX_POPUP=26
    RADIUS_MIN_OSD=2;              RADIUS_MAX_OSD=16
    # 9999 rather than a pixel ceiling: that is the sentinel `default` and
    # `rounded` both ship (see TOKEN_RADIUS_BUTTON above), and a bound lower
    # than it would make the shipped value itself unreachable by hand.
    RADIUS_MIN_BUTTON=4;           RADIUS_MAX_BUTTON=9999
}

# The `default` row and the literals above are the same numbers written twice,
# which is the one thing this file exists to prevent — so it is asserted rather
# than trusted. tools/check-tokens.sh calls this.
radius_preset_matches_shipped() {
    local w="$TOKEN_RADIUS_WINDOW" m="$TOKEN_RADIUS_MENU" \
          q="$TOKEN_RADIUS_QUICK_SETTINGS" n="$TOKEN_RADIUS_NOTIFICATION" \
          d="$TOKEN_RADIUS_DIALOG" p="$TOKEN_RADIUS_POPUP" o="$TOKEN_RADIUS_OSD" \
          b="$TOKEN_RADIUS_BUTTON"
    radius_preset_values default
    local rc=0
    [ "$w" = "$TOKEN_RADIUS_WINDOW" ] || rc=1
    [ "$m" = "$TOKEN_RADIUS_MENU" ] || rc=1
    [ "$q" = "$TOKEN_RADIUS_QUICK_SETTINGS" ] || rc=1
    [ "$n" = "$TOKEN_RADIUS_NOTIFICATION" ] || rc=1
    [ "$d" = "$TOKEN_RADIUS_DIALOG" ] || rc=1
    [ "$p" = "$TOKEN_RADIUS_POPUP" ] || rc=1
    [ "$o" = "$TOKEN_RADIUS_OSD" ] || rc=1
    [ "$b" = "$TOKEN_RADIUS_BUTTON" ] || rc=1
    # Leave the shipped values standing whatever the answer was.
    TOKEN_RADIUS_WINDOW="$w"; TOKEN_RADIUS_MENU="$m"
    TOKEN_RADIUS_QUICK_SETTINGS="$q"; TOKEN_RADIUS_NOTIFICATION="$n"
    TOKEN_RADIUS_DIALOG="$d"; TOKEN_RADIUS_POPUP="$p"; TOKEN_RADIUS_OSD="$o"
    TOKEN_RADIUS_BUTTON="$b"
    return $rc
}

# ---------- Blur My Shell sigmas ----------
#
# Every pipeline uses the native_static_gaussian_blur effect, whose cost scales
# with radius. Two things compound that:
#
#   1. hacks-level=2 (dconf/core.ini) turns off clipped redraws, which is the
#      fix for blur actors going stale when what is behind them moves. The cost
#      is a full-screen repaint every frame, for everything.
#   2. The panel is the only surface that is both always visible and always
#      blurred, so it is the only one paying that multiplier continuously
#      rather than for the few seconds a popup is open.
#
# Sigma changes here are design decisions with a measurable cost. Change one,
# measure it in the preview harness, and record the number — do not batch them.

# Measured, not assumed: dropping this to 20 and back over three preview runs
# moved the median not at all (22/22/22) and the p90 by less than the noise
# between two identical runs (28/29/31). The panel being always-on makes it the
# most expensive *pipeline*, but the cost that matters is Blur My Shell running
# at all — which is what --no-blur removes and what actually measures. Do not
# lower this expecting a GPU win; lower it only if you want a softer panel.
TOKEN_SIGMA_PANEL=30
TOKEN_SIGMA_APPFOLDER=50        # transient, but an outlier above every other
                                # pipeline's ~30 ceiling for no recorded reason.
TOKEN_SIGMA_POPUP=30
TOKEN_SIGMA_WINDOW_LIST=30
# Only ever applied when --app-transparency is on: the window blur is off in
# dconf/core.ini and install.sh turns it on to follow that flag. Leaving it on
# by default was the single most expensive thing in this preset — overview p90
# GPU busy 99% against 28% with it off, on an RX 7600 — and with the window at
# 94% opacity almost none of it reached the screen.
TOKEN_SIGMA_APPLICATIONS=12
TOKEN_SIGMA_DASH_TO_DOCK=4      # the cheap end of the range, kept as reference.

# ---------- App transparency ----------
#
# The level css/gtk4-transparency.css is *written* at. install_transparency_css
# in lib/steps.sh rescales every alpha in the installed copy relative to this
# baseline, so that the ladder between surfaces survives being retuned. It is
# therefore not merely a default — changing it without rewriting the sheet's
# own alphas changes what every other level means.
#
#   install.sh                    --app-transparency default and its help text
#   lib/steps.sh                  SHIPPED, in install_transparency_css
#   css/gtk4-transparency.css     the alpha() values themselves
TOKEN_APP_TRANSPARENCY_SHIPPED=0.92

# How much of the theme's own colour survives in a translucent app window, as a
# percentage; the rest is black. Darkening and thinning are opposite knobs —
# --app-transparency decides how much shows through, this decides how dark what
# remains is — and the second is what keeps text legible as the first goes up.
#
# It matters most with --no-blur, where what shows through is the wallpaper at
# full brightness rather than a blur. At 100 the window is the theme's colour
# and a bright wallpaper prints straight through it.
#
# Unlike the level above this is not rescaled per install — it is a design
# decision, written literally in both spellings in the sheet and checked against
# this token. Change it here, run tools/check-tokens.sh, and it names the lines
# that still disagree. The mix() weight is the complement (100 - this).
#
#   css/gtk4-transparency.css   the @define-color and :root tint blocks
TOKEN_APP_TINT=45

# ---------- Not tokens, deliberately ----------
#
# The accent colour is already live-plumbed through GNOME's own machinery: the
# shell CSS reads -st-accent-color and the GTK CSS reads @accent_bg_color, so
# Settings -> Appearance recolours the desktop without a file being touched.
# Pinning it here would be a downgrade. See the README's "Custom colours".
#
# Nor can it be an arbitrary hex, which is worth writing down because it looks
# like it should be. -st-accent-color is not a CSS property St will let anything
# assign: it is a read-only keyword backed by the C enum StSystemAccentColor,
# whose nine values are exactly the nine accent names, resolved from the
# gsetting by st_theme_context_get_accent_color(). There is no assignment of it
# anywhere in gnome-shell's own stylesheet — only 186 reads. So a
# `stage { -st-accent-color: #hex }` rule appended after the theme cannot work,
# however late in the cascade it lands.
#
# GTK4's @accent_bg_color *is* an ordinary named colour and would override
# cleanly, which is the trap: a custom hex is reachable for every app window and
# for none of the shell. That is not a colour scheme, it is two of them, so the
# window offers the nine names and no picker.
#
# Values that appear exactly once (the .quick-slider capsule at 26px, the
# gtk4 field radius at 10px, the tooltip at 12px) are not listed. A token for a
# value with one consumer cannot catch drift, and only adds a second place to
# forget to update.
