#!/usr/bin/env bash
# The inside of tools/preview.sh: this runs on the private bus, with HOME and
# the XDG directories already pointed at the candidate profile. Do not run it
# directly — it expects those to be redirected already, and run against your own
# HOME it would overwrite the GSettings keyfile and the theme of the desktop you
# are using.
set -uo pipefail

REPO_ROOT="$TG_REPO_ROOT"
PROFILE="$TG_PROFILE"
SHOTS="$TG_SHOTS"
LOG="$PROFILE/shell.log"

say() { printf '\033[1;36m::\033[0m %s\n' "$*"; }

# Settings go through GLib's keyfile backend, not dconf.
#
# dconf does not work in here. `dconf write` and `gsettings set` both exit 0 on
# this private bus and then read back empty, with no database ever created —
# the dconf-service the client talks to over D-Bus never persists anything.
# That is unusable for seeding a session.
#
# The keyfile backend takes dconf out of the picture completely: settings are
# one plain file that this script writes and the shell reads. It is also the
# stronger isolation of the two. dbus-run-session prevents the live desktop's
# dconf-service from *hearing* a write; the keyfile backend means there is no
# dconf write to make. The preset that once rewrote the real session's OSD keys
# cannot reach it through a mechanism that is not being used.
#
# Group names are the schema path with slashes, and values are GVariant text —
# the same syntax dconf/core.ini already holds, so its bodies transfer
# unchanged and only the section headers need the schema prefix.
KEYFILE="$XDG_CONFIG_HOME/glib-2.0/settings/keyfile"
mkdir -p "$(dirname "$KEYFILE")"

say "seeding settings from dconf/core.ini"
PREVIEW_THEME="${AURA_GLASS_THEME:-Aura-Glass}"
[ -d "$HOME/.themes/$PREVIEW_THEME" ] || [ ! -d "$HOME/.themes/Tahoe-Dark" ] \
    || PREVIEW_THEME="Tahoe-Dark"

python3 - "$REPO_ROOT/dconf/core.ini" "$KEYFILE" "$PREVIEW_THEME" <<'PY'
import os
import sys

src, dst, theme = sys.argv[1], sys.argv[2], sys.argv[3]
PREFIX = "org/gnome/shell/extensions/"

out = [
    "# Generated by tools/preview-session.sh — not part of the installed",
    "# desktop. Edit dconf/core.ini instead.",
    "",
    "[org/gnome/shell]",
    # Set here rather than through the extensions D-Bus API, which needs a
    # shell that is already running.
    # Blur My Shell is left out of solid mode entirely rather than switched
    # off, matching what install.sh does: an extension that is loaded still
    # builds a background actor per surface even with every component disabled.
    "enabled-extensions=[%s]" % ", ".join(
        "'%s'" % u for u in
        ["user-theme@gnome-shell-extensions.gcampax.github.com"]
        + ([] if os.environ.get("TG_SOLID") == "1" else ["blur-my-shell@aunetx"])
        + ["openbar@neuromorph", "custom-osd@neuromorph",
           os.environ["TG_DRIVER_UUID"]]),
    "disable-user-extensions=false",
    "",
    "[org/gnome/desktop/interface]",
    "color-scheme='prefer-dark'",
    "gtk-theme='Adwaita'",
    "",
]

for line in open(src, encoding="utf-8"):
    line = line.rstrip("\n")
    stripped = line.strip()
    if stripped.startswith("[") and stripped.endswith("]"):
        # dconf/core.ini is written relative to /org/gnome/shell/extensions/,
        # which is the path install.sh loads it into.
        out.append("[%s%s]" % (PREFIX, stripped[1:-1]))
    else:
        out.append(line)

if os.environ.get("TG_SOLID") == "1":
    # After core.ini, never before. A keyfile takes the *last* value for a key,
    # so an overlay written first is silently overridden by the thing it is
    # meant to override — which showed up as a top bar that stayed transparent
    # because core.ini's near-zero bgalpha won. load_dconf applies it in this order
    # too.
    out.append("# --- solid mode overlay (dconf/solid.ini) ---")
    for line in open(os.path.join(os.path.dirname(src), "solid.ini"),
                     encoding="utf-8"):
        line = line.rstrip("\n")
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            out.append("[%s%s]" % (PREFIX, stripped[1:-1]))
        else:
            out.append(line)
    out.append("")

# The shell theme name is under the same prefix, but the preset does not carry
# it as a section of its own.
out += ["", "[org/gnome/shell/extensions/user-theme]", "name='%s'" % theme, ""]

open(dst, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("   %d groups -> %s" % (sum(1 for l in out if l.startswith("[")), dst))
PY

# Every process in this session has to agree on the backend, or the shell reads
# a dconf that has none of the above.
export GSETTINGS_BACKEND=keyfile

say "starting gnome-shell (headless, $TG_RES)"
gnome-shell --headless --virtual-monitor "$TG_RES" \
            --wayland-display="$TG_DISPLAY" > "$LOG" 2>&1 &
SHELL_PID=$!

CLIENTS=()
cleanup() {
    local p
    for p in "${CLIENTS[@]:-}"; do [ -n "$p" ] && kill "$p" 2>/dev/null; done
    kill "$SHELL_PID" 2>/dev/null
    wait "$SHELL_PID" 2>/dev/null
}
trap cleanup EXIT

# Wait for the shell to own its name rather than sleeping a guess at it.
for _ in $(seq 1 80); do
    gdbus introspect --session --dest org.gnome.Shell \
        --object-path /org/gnome/Shell >/dev/null 2>&1 && break
    sleep 0.5
done
if ! gdbus introspect --session --dest org.gnome.Shell \
        --object-path /org/gnome/Shell >/dev/null 2>&1; then
    echo "!! the shell never came up. Last lines of $LOG:" >&2
    tail -20 "$LOG" >&2
    exit 1
fi
say "shell is up on wayland display '$TG_DISPLAY'"

# Which extensions actually loaded. A theme that renders stock is nearly always
# this, and it is invisible in a screenshot until you know to look.
say "extension state"
python3 "$REPO_ROOT/tools/preview-extensions.py" \
    user-theme@gnome-shell-extensions.gcampax.github.com \
    blur-my-shell@aunetx openbar@neuromorph custom-osd@neuromorph

shot() {
    python3 "$REPO_ROOT/tools/preview-shot.py" "$SHOTS/$1.png" >/dev/null 2>&1 \
        && printf '   %s.png\n' "$1" \
        || printf '   %s.png FAILED\n' "$1"
}

overview() {
    gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell \
        --method org.freedesktop.DBus.Properties.Set \
        org.gnome.Shell OverviewActive "<$1>" >/dev/null 2>&1
    sleep 2
}

launch() {
    WAYLAND_DISPLAY="$TG_DISPLAY" GDK_BACKEND=wayland "$@" >/dev/null 2>&1 &
    CLIENTS+=($!)
    sleep 5
}

# The driver extension opens the surfaces that an idle desktop never shows.
# Most of this project's shell CSS paints those, so without it the screenshots
# cover the panel and nothing else.
driver() {
    local method="$1"; shift
    gdbus call --session --dest org.auraGlass.PreviewDriver \
        --object-path /org/auraGlass/PreviewDriver \
        --method "org.auraGlass.PreviewDriver.$method" "$@" >/dev/null 2>&1
}

DRIVER=0
for _ in $(seq 1 20); do
    driver Ping && { DRIVER=1; break; }
    sleep 0.5
done
[ "$DRIVER" = 1 ] || echo "   driver extension did not answer — menu, notification
   and OSD shots will be skipped. Check that $TG_DRIVER_UUID loaded above."

# GPU sampling runs alongside everything below, so the number covers the same
# work every time. gpu_busy_percent is the zero-install baseline; radeontop
# would break it down per block but is not needed to compare two sigmas.
# tools/gpu-sample.py knows which interface this machine's driver exposes, and
# says so plainly when it exposes none — an Intel iGPU has no sysfs busy figure
# at all, and printing 0 there would read as an idle GPU rather than as a
# missing measurement.
GPU_CARD=""
if [ "$TG_GPU" = 1 ]; then
    if python3 "$REPO_ROOT/tools/gpu-sample.py" --probe; then
        for _c in /sys/class/drm/card*/device/gpu_busy_percent; do
            [ -r "$_c" ] && { GPU_CARD="$_c"; break; }
        done
    fi
    if [ -n "$GPU_CARD" ]; then
        say "sampling $GPU_CARD"
        ( while :; do cat "$GPU_CARD" 2>/dev/null; sleep 0.1; done > "$PROFILE/gpu.samples" ) &
        CLIENTS+=($!)
    else
        echo "   no gpu_busy_percent on this machine — skipping GPU sampling"
    fi
fi

say "capturing"
# The shell boots into the overview, so the plain desktop has to be asked for.
overview false
shot 01-desktop
overview true
shot 02-overview
overview false

launch nautilus
shot 03-nautilus
launch gnome-text-editor
shot 04-text-editor

# The overview with windows in it, which 02-overview cannot show because it is
# taken before anything is launched. Window blur is an actor of its own, sitting
# under the window as a child of the window actor, so the overview's previews
# clone it along with the window — and with `blur-on-overview: false` it has no
# business painting there. Upstream let it, and what it painted was the pixels
# it last sampled on the desktop, changing whenever a preview was hovered.
# patches/blur-my-shell-overview.patch is what stops it; this is the shot that
# would show it coming back.
overview true
shot 04b-overview-windows
overview false

# css/gtk3-tweaks.css is the one sheet nothing else here covers. Every app in
# the roster above is GTK4, and the GTK3 half of Tahoe-Dark ships as a gresource
# — so those rules can only be seen against a real GTK3 window, and until now
# they were never seen at all.
#
# Which GTK3 apps a machine has varies, and none of them is worth making a
# dependency for a screenshot, so this takes the first one that happens to be
# installed and says so plainly when there is none.
GTK3_APP=""
for c in nm-connection-editor pavucontrol lxappearance gnome-disks \
         transmission-gtk galculator; do
    command -v "$c" >/dev/null 2>&1 && { GTK3_APP="$c"; break; }
done
if [ -n "$GTK3_APP" ]; then
    launch "$GTK3_APP"
    shot 05-gtk3
else
    echo "   no GTK3 app installed — css/gtk3-tweaks.css gets no shot this run"
    echo "   (any one of: nm-connection-editor pavucontrol lxappearance gnome-disks)"
fi

if [ "$DRIVER" = 1 ]; then
    # Each of these is the only coverage a whole sheet gets:
    #   quick settings  -> css/shell-10-quick-settings.css, shell-40-quick-toggles.css
    #   date menu       -> css/shell-20-popup-menus.css (.datemenu-popover at 33)
    #   dialog          -> css/shell-50-dialogs.css
    #   notification    -> css/shell-30-notifications.css
    #   OSD             -> the Custom OSD pill and its blur
    driver OpenQuickSettings; sleep 2; shot 06-quick-settings
    driver CloseMenus;        sleep 1
    driver OpenDateMenu;      sleep 2; shot 07-date-menu
    driver CloseMenus;        sleep 1

    # The dialog is modal and covers most of the screen, so it is opened and
    # closed around its own shot rather than left standing like the app windows.
    driver ShowDialog "Restart" "The system will restart automatically."
    sleep 2; shot 08-dialog
    driver HideDialog; sleep 1

    # The app switcher (Alt+Tab / Super+Tab) exercises .switcher-list
    # .item-box:selected, which this project paints with -st-accent-color.
    # Needs at least two windows open to show a populated list.
    driver ShowSwitcher
    sleep 2; shot 09-switcher
    driver HideSwitcher; sleep 1

    # The OSD goes before the notification, and not the other way round,
    # because the OSD can be dismissed on command and a notification banner
    # cannot — it sits there for several seconds and lands in whatever is shot
    # next. Doing the banner last means nothing has to wait for it.
    driver ShowOsd "audio-volume-high-symbolic" 0.65
    sleep 1; shot 10-osd
    driver HideOsd; sleep 2

    driver Notify "aura-glass" "Notification banner, for the CSS under test."
    sleep 1; shot 11-notification
fi

if [ "$TG_GPU" = 1 ] && [ -n "$GPU_CARD" ]; then
    say "GPU busy% over the run"
    python3 - "$PROFILE/gpu.samples" <<'PY'
import sys
try:
    v = [int(x) for x in open(sys.argv[1]) if x.strip().isdigit()]
except OSError:
    v = []
if v:
    v.sort()
    print("   samples %d  min %d  median %d  p90 %d  max %d"
          % (len(v), v[0], v[len(v)//2], v[int(len(v)*0.9)], v[-1]))
else:
    print("   no samples collected")
PY
fi

if [ "$TG_KEEP" = 1 ]; then
    say "session held open. Another terminal can reach it with:"
    echo "   WAYLAND_DISPLAY=$TG_DISPLAY <app>"
    echo "   (only from inside this bus — press enter here to tear it down)"
    read -r _
fi
